// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xiylmhpaoefihsuxsmgr.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InhpeWxtaHBhb2VmaWhzdXhzbWdyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDU3NDYxNTAsImV4cCI6MjA2MTMyMjE1MH0.oEcqVrTHBp9EigdU3Ms9v84xRTqnBMdTK32fhdoG5ZI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);